"""Plot Phase3 Baseline vs CAC radar charts from the aggregated CSV.

Input: results/ablation/phase3_best_all_systems_*.csv (generated by run_final_eval.py)
Output: results/plots/phase3_radar_*.png

Two visualization modes:
- absolute (default): Baseline and CAC plotted with *per-system local normalization*
  so each subplot has strong contrast even for low-scale systems like JPetStore.
- relative-gain: plot CAC relative improvement over Baseline, with Baseline as neutral reference.
  This is paper-friendly when systems have very different absolute scales.

Metrics:
- Q (higher better)
- 1 - IFN_Ratio (higher better)
- SvcFit (continuous closeness to the center of target range; higher better)

NOTE: The old placeholder "Balance" axis was removed; if you want balance, add a real metric
(e.g., 1 - Gini(cluster_sizes)) into the CSV and re-introduce it explicitly.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
import numpy as np


@dataclass
class Row:
    system: str
    dpep_cap: float
    target_min: int
    target_max: int
    baseline_services: int | None
    baseline_q: float | None
    baseline_ifn_ratio: float | None
    cac_services: int | None
    cac_q: float | None
    cac_ifn_ratio: float | None


def _to_int(v: str) -> int | None:
    v = (v or "").strip()
    if not v or v.lower() == "none":
        return None
    return int(float(v))


def _to_float(v: str) -> float | None:
    v = (v or "").strip()
    if not v or v.lower() == "none":
        return None
    return float(v)


def load_csv(path: Path) -> List[Row]:
    rows: List[Row] = []
    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append(
                Row(
                    system=r["system"],
                    dpep_cap=float(r.get("dpep_cap") or 0.0),
                    target_min=int(float(r.get("target_min") or 0)),
                    target_max=int(float(r.get("target_max") or 0)),
                    baseline_services=_to_int(r.get("baseline_services", "")),
                    baseline_q=_to_float(r.get("baseline_q", "")),
                    baseline_ifn_ratio=_to_float(r.get("baseline_ifn_ratio", "")),
                    cac_services=_to_int(r.get("cac_services", "")),
                    cac_q=_to_float(r.get("cac_q", "")),
                    cac_ifn_ratio=_to_float(r.get("cac_ifn_ratio", "")),
                )
            )
    return rows


def _minmax(values: List[float], fallback=(0.0, 1.0)) -> Tuple[float, float]:
    vals = [v for v in values if v is not None and np.isfinite(v)]
    if not vals:
        return fallback
    mn, mx = float(min(vals)), float(max(vals))
    if mx <= mn:
        return (mn, mn + 1e-9)
    return mn, mx


def _norm(v: float | None, mn: float, mx: float, default: float = 0.0) -> float:
    if v is None or not np.isfinite(v):
        return float(default)
    if mx <= mn:
        return 0.0
    return float((v - mn) / (mx - mn))


def service_closeness(services: int | None, tmin: int, tmax: int) -> float:
    """Score in [0,1], peak at the center of target range."""
    if services is None:
        return 0.0
    center = 0.5 * (tmin + tmax)
    radius = max(1.0, 0.5 * (tmax - tmin))
    d = abs(float(services) - float(center)) / float(radius)
    return float(max(0.0, 1.0 - d))


def plot_radar(ax, labels: List[str], values: List[float], *, color: str, name: str, linestyle: str = "-"):
    n = len(labels)
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False).tolist()
    # close the polygon
    values = values + values[:1]
    angles = angles + angles[:1]

    ax.plot(angles, values, color=color, linewidth=2, linestyle=linestyle, label=name)
    ax.fill(angles, values, color=color, alpha=0.15)


def _norm_pair(b: float | None, c: float | None, default: float = 0.0) -> tuple[float, float]:
    """Local min-max normalize a baseline/cac pair to [0,1] for visual contrast."""
    vals = [v for v in (b, c) if v is not None and np.isfinite(v)]
    if not vals:
        return float(default), float(default)
    mn, mx = float(min(vals)), float(max(vals))
    if mx <= mn:
        return 0.5, 0.5
    bn = (float(b) - mn) / (mx - mn) if b is not None and np.isfinite(b) else float(default)
    cn = (float(c) - mn) / (mx - mn) if c is not None and np.isfinite(c) else float(default)
    return float(bn), float(cn)


def _rel_gain(
    b: float | None,
    c: float | None,
    *,
    eps: float = 1e-9,
    clip: float = 2.0,
    missing_baseline: float = 0.75,
) -> float:
    """Relative gain (CAC-B)/|B| mapped to [0,1] by clipping.

    - If baseline missing/invalid: return `missing_baseline` (in [0,1]) so CAC doesn't collapse to center.
    - clip=2.0 means +200% maps to 1.0 and -200% maps to 0.0.
    """
    if c is None or (not np.isfinite(c)):
        return 0.0

    # baseline missing (N/A) => keep CAC visible; interpret as "robustness" rather than failure
    if b is None or (not np.isfinite(b)):
        return float(max(0.0, min(1.0, missing_baseline)))

    denom = abs(float(b)) + float(eps)
    g = (float(c) - float(b)) / denom
    g = max(-float(clip), min(float(clip), g))
    # map [-clip, clip] -> [0,1]
    return float((g + float(clip)) / (2.0 * float(clip)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--csv",
        type=str,
        default=None,
        help="Path to phase3_best_all_systems_*.csv (default: latest in results/ablation)",
    )
    ap.add_argument("--out_dir", type=str, default="results/plots")
    ap.add_argument(
        "--mode",
        choices=["absolute", "relative-gain"],
        default="absolute",
        help="Radar plotting mode. absolute uses per-system local normalization; relative-gain uses (CAC-B)/|B|.",
    )
    ap.add_argument(
        "--gain_clip",
        type=float,
        default=2.0,
        help="For --mode relative-gain: clip relative gain to [-clip, +clip] before mapping to [0,1] (default 2.0 => ±200%).",
    )
    ap.add_argument(
        "--missing_baseline_gain",
        type=float,
        default=0.75,
        help="For --mode relative-gain: value in [0,1] to use when Baseline is N/A for a metric (default 0.75).",
    )
    ap.add_argument(
        "--baseline_ref",
        type=float,
        default=0.5,
        help="For --mode relative-gain: Baseline reference polygon value in [0,1] (default 0.5).",
    )
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[4]
    ablation = root / "results" / "ablation"

    if args.csv:
        csv_path = Path(args.csv)
        if not csv_path.is_absolute():
            csv_path = (root / csv_path).resolve()
    else:
        candidates = sorted(ablation.glob("phase3_best_all_systems_*.csv"))
        if not candidates:
            raise SystemExit(f"No CSV found in {ablation}. Run run_final_eval.py first.")
        csv_path = candidates[-1]

    rows = load_csv(csv_path)

    # Collect global min/max for normalization
    q_vals = []
    i_vals = []
    for r in rows:
        if r.baseline_q is not None:
            q_vals.append(r.baseline_q)
        if r.cac_q is not None:
            q_vals.append(r.cac_q)
        if r.baseline_ifn_ratio is not None:
            i_vals.append(1.0 - r.baseline_ifn_ratio)
        if r.cac_ifn_ratio is not None:
            i_vals.append(1.0 - r.cac_ifn_ratio)

    q_min, q_max = _minmax(q_vals, fallback=(0.0, 0.2))
    inv_ifn_min, inv_ifn_max = _minmax(i_vals, fallback=(0.0, 1.0))

    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = (root / out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # 3-axis radar (paper-friendly)
    labels = ["Q", "1-IFN_Ratio", "SvcFit"]

    # 2x2 subplots, one per system
    fig = plt.figure(figsize=(12, 10))
    for idx, r in enumerate(rows):
        ax = plt.subplot(2, 2, idx + 1, polar=True)
        ax.set_title(r.system, y=1.10)
        ax.set_xticks(np.linspace(0, 2 * np.pi, len(labels), endpoint=False))
        ax.set_xticklabels(labels)
        ax.set_yticklabels([])
        ax.set_ylim(0, 1)

        # Continuous SvcFit in [0,1]
        b_svcfit = service_closeness(r.baseline_services, r.target_min, r.target_max)
        c_svcfit = service_closeness(r.cac_services, r.target_min, r.target_max)

        baseline_na_notes: List[str] = []

        if args.mode == "relative-gain":
            # Baseline as a stable reference polygon (so the plot reads as "blue expands beyond gray")
            ref = float(max(0.0, min(1.0, args.baseline_ref)))
            b_vals = [ref, ref, ref]

            # Compute CAC gains; if baseline metric is N/A, keep CAC visible and annotate.
            if r.baseline_q is None:
                baseline_na_notes.append("Q")
            if r.baseline_ifn_ratio is None:
                baseline_na_notes.append("IFN")
            if r.baseline_services is None:
                baseline_na_notes.append("Svc")

            c_vals = [
                _rel_gain(
                    r.baseline_q,
                    r.cac_q,
                    clip=float(args.gain_clip),
                    missing_baseline=float(args.missing_baseline_gain),
                ),
                _rel_gain(
                    (1.0 - r.baseline_ifn_ratio) if r.baseline_ifn_ratio is not None else None,
                    (1.0 - r.cac_ifn_ratio) if r.cac_ifn_ratio is not None else None,
                    clip=float(args.gain_clip),
                    missing_baseline=float(args.missing_baseline_gain),
                ),
                _rel_gain(
                    b_svcfit if r.baseline_services is not None else None,
                    c_svcfit if r.cac_services is not None else None,
                    clip=float(args.gain_clip),
                    missing_baseline=float(args.missing_baseline_gain),
                ),
            ]
        else:
            # absolute (per-system local normalization for Q and 1-IFN_Ratio)
            bq, cq = _norm_pair(r.baseline_q, r.cac_q, default=0.0)
            bi, ci = _norm_pair(
                (1.0 - r.baseline_ifn_ratio) if r.baseline_ifn_ratio is not None else None,
                (1.0 - r.cac_ifn_ratio) if r.cac_ifn_ratio is not None else None,
                default=0.0,
            )

            b_vals = [bq, bi, b_svcfit]
            c_vals = [cq, ci, c_svcfit]

        # In relative-gain, show baseline reference as dashed gray to avoid "algorithm polygon" confusion
        base_ls = "--" if args.mode == "relative-gain" else "-"
        plot_radar(ax, labels, b_vals, color="#777777", name="Baseline", linestyle=base_ls)
        plot_radar(ax, labels, c_vals, color="#1f77b4", name="CAC-Final")

        # Annotate cap + target
        ax.text(
            0.5,
            -0.12,
            f"cap={r.dpep_cap:.2f}, target=[{r.target_min},{r.target_max}], mode={args.mode}",
            transform=ax.transAxes,
            ha="center",
            va="top",
            fontsize=9,
        )

        # If baseline had N/A, explicitly mark it (prevents the "hard right angle" reviewer reaction)
        if baseline_na_notes and args.mode == "relative-gain":
            ax.text(
                0.5,
                -0.19,
                f"Baseline N/A: {','.join(baseline_na_notes)}",
                transform=ax.transAxes,
                ha="center",
                va="top",
                fontsize=8,
                color="#555555",
            )

    handles, labels_ = plt.gca().get_legend_handles_labels()
    fig.legend(handles, labels_, loc="lower center", ncol=2)
    title = "Phase3 Radar (per-system normalized)" if args.mode == "absolute" else "Phase3 Radar (relative gains vs Baseline)"
    fig.suptitle(title, y=0.98)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    suffix = "local" if args.mode == "absolute" else "relgain"
    out_path = out_dir / f"phase3_radar_{suffix}_{ts}.png"
    fig.tight_layout(rect=[0, 0.05, 1, 0.95])
    fig.savefig(out_path, dpi=220)

    print(f"[OK] input_csv={csv_path}")
    print(f"[OK] saved={out_path}")


if __name__ == "__main__":
    main()
